### ISSUE TITLE
Sequential test suits

### ISSUE THREAD

**Issue by PaulNBarron** [tcunit/ExampleProjects#1] opened 2020-03-26 15:33 UTC
Hi,
Is it possible to run the test suits sequentially? For example if I have TestSuite1_FB and TestSuite2_FB is it possible to wait until TestSuite1_FB has finished executing before starting TestSuite2_FB?
Thanks

**Comment by sagatowski** [comment] 2020-05-15 11:51
Duplicate of https://github.com/tcunit/TcUnit/issues/97.

**Closed as completed by sagatowski** 2020-05-15 11:51 UTC
